version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "8080:8080"
    networks:
      - frontend_net
    depends_on:
      - api

  api:
    image: node:alpine
    working_dir: /app
    command: sh -c "echo 'console.log(\"Hello from Node API\");' > app.js && node app.js"
    ports:
      - "3000:3000"  # Exponer un puerto si es necesario
    networks:
      - backend_net
    environment:
      - DB_HOST=database
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - backend_net

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - frontend_net

networks:
  frontend_net:
  backend_net:
    internal: true
